export * from './handle-api'
export * from './handle-app-js'
export * from './handle-favicon'
export * from './handle-js'
export * from './handle-options'
export * from './handle-other'
export * from './handle-sitemap'
